name: Workflow with conda dependencies

on: [push]

jobs:
  example-1:
    name: Ex1 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, self-hosted]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          #miniforge-version: latest
          activate-environment: ${GITHUB_WORKSPACE}/whatever
          remove-profiles: false
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list